import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import Header from '@/components/Header/Header';
import Header2 from '@/components/Header2/Header';
import Footer from '@/components/footer';
import "@/scss/main.scss"

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen max-w-4xl mx-auto'>
          {/* <Header /> */}
          <Header2 />
          <div className='flex-grow'>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
